"""
This module was autogenerated by gale.

Every setting here overrides gale.conf.global_settings' default for
gale.game.Game -- anything you remove (or never had) falls back to
gale's own default automatically; see gale.conf for the full list.
You can also add settings of your own here (for instance PLAYER_SPEED)
and read them back the same way, with `from gale.conf import settings`.
"""
import pathlib

import pygame

from gale import frames
from gale import input_handler

# No need to call pygame.mixer.init()/pygame.font.init() here: importing
# anything under gale (frames/input_handler above, for instance) already
# calls pygame.init(), which initializes every subsystem pygame ships
# with, mixer and font included -- and does so without raising if, say,
# no audio device is available, unlike calling pygame.mixer.init() directly.

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_ESCAPE, 'quit')
input_handler.InputHandler.set_mouse_click_action(input_handler.MOUSE_BUTTON_1, 'mouse_click')
input_handler.InputHandler.set_mouse_motion_action(None, 'mouse_motion')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, 'confirm')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_UP, 'navigate_up')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_DOWN, 'navigate_down')

TITLE = 'Rubik Cube'

# Size we want to emulate
VIRTUAL_WIDTH = 480
VIRTUAL_HEIGHT = 270


def _window_size_for_current_screen() -> tuple[int, int]:
    """
    Computes a "normal" window size for the user's screen: it takes up
    a comfortable fraction of the detected resolution (not fullscreen)
    without distorting the VIRTUAL_WIDTH/VIRTUAL_HEIGHT aspect ratio.
    If the screen can't be detected (for instance, no graphical
    environment), it falls back to a reasonable fixed size.
    """
    screen_fraction = 0.85
    default_width, default_height = 1280, 720

    screen_info = pygame.display.Info()
    screen_width, screen_height = screen_info.current_w, screen_info.current_h
    if screen_width <= 0 or screen_height <= 0:
        return default_width, default_height

    aspect_ratio = VIRTUAL_WIDTH / VIRTUAL_HEIGHT
    max_width = screen_width * screen_fraction
    max_height = screen_height * screen_fraction

    width = min(max_width, max_height * aspect_ratio)
    height = width / aspect_ratio
    return round(width), round(height)


# Size of our actual window: a fraction of the detected screen,
# keeping the virtual resolution's aspect ratio.
WINDOW_WIDTH, WINDOW_HEIGHT = _window_size_for_current_screen()

BASE_DIR = pathlib.Path(__file__).parent

TEXTURES = {
    "shuffle": pygame.image.load(BASE_DIR / "assets" / "graphics" / "shuffle.png"),
    "auto": pygame.image.load(BASE_DIR / "assets" / "graphics" / "auto.png"),
    "eye_open": pygame.image.load(BASE_DIR / "assets" / "graphics" / "eye_open.png"),
    "eye_closed": pygame.image.load(BASE_DIR / "assets" / "graphics" / "eye_closed.png"),
    "search": pygame.image.load(BASE_DIR / "assets" / "graphics" / "search.png"),
    "undo": pygame.image.load(BASE_DIR / "assets" / "graphics" / "undo.png"),
    "redo": pygame.image.load(BASE_DIR / "assets" / "graphics" / "redo.png"),
}

# Register your frames, for instance:
# FRAMES = {
#     'my_frames': frames.generate_frames(TEXTURES['my_texture'], 16, 16)
# }
FRAMES = {}

# Register your sound from the sounds folder, for instance:
# SOUNDS = {
#     'my_sound': pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "my_sound.wav"),
# }
SOUNDS = {}

# Register your fonts from the fonts folder, for instance:
# FONTS = {
#     'small': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "font.ttf", 8)
# }
FONTS = {
    # Font for the face-guide letters (U/D/L/R/F/B) -- see
    # PlayState._draw_eye_button and view_3d.draw_face_guide.
    # Font(None, ...) uses pygame's default font, no .ttf file of our
    # own is needed.
    "guide": pygame.font.Font(None, 15),
    # Small font rendered without antialiasing at MenuState/
    # InstructionsState's title/button sizes, then upscaled with
    # nearest-neighbor scaling for a blocky "pixel art" look -- see
    # MenuState._pixel_text / _pixel_text_rainbow.
    "pixel_title": pygame.font.Font(None, 19),
    "pixel_button": pygame.font.Font(None, 14),
    # Plain (antialiased) body font for InstructionsState's control
    # list -- legible at small size, no pixel-scaling trick needed.
    "body": pygame.font.Font(None, 14),
    "body_bold": pygame.font.Font(None, 14),
    # Digits for PlayState's scramble timer, rendered blocky/pixel-art
    # style (see PlayState._render_pixel_text) same trick as
    # "pixel_title"/"pixel_button" above.
    "timer": pygame.font.Font(None, 18),
}
FONTS["guide"].set_bold(True)
FONTS["pixel_title"].set_bold(True)
FONTS["pixel_button"].set_bold(True)
FONTS["body_bold"].set_bold(True)
FONTS["timer"].set_bold(True)
