"""
This module was autogenerated by gale.

Every setting here overrides gale.conf.global_settings' default for
gale.game.Game -- anything you remove (or never had) falls back to
gale's own default automatically; see gale.conf for the full list.
You can also add settings of your own here (for instance PLAYER_SPEED)
and read them back the same way, with `from gale.conf import settings`.
"""
import pathlib

import pygame

from gale import frames
from gale import input_handler

# No need to call pygame.mixer.init()/pygame.font.init() here: importing
# anything under gale (frames/input_handler above, for instance) already
# calls pygame.init(), which initializes every subsystem pygame ships
# with, mixer and font included -- and does so without raising if, say,
# no audio device is available, unlike calling pygame.mixer.init() directly.

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_ESCAPE, 'quit')
input_handler.InputHandler.set_mouse_click_action(input_handler.MOUSE_BUTTON_1, 'mouse_click')
input_handler.InputHandler.set_mouse_motion_action(None, 'mouse_motion')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, 'confirm')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_UP, 'navigate_up')
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_DOWN, 'navigate_down')

TITLE = 'Rubik Cube'

# Size we want to emulate
VIRTUAL_WIDTH = 480
VIRTUAL_HEIGHT = 270


def _window_size_for_current_screen() -> tuple[int, int]:
    """
    Computes a "normal" window size for the user's screen: it takes up
    a comfortable fraction of the detected resolution (not fullscreen)
    without distorting the VIRTUAL_WIDTH/VIRTUAL_HEIGHT aspect ratio.
    If the screen can't be detected (for instance, no graphical
    environment), it falls back to a reasonable fixed size.
    """
    screen_fraction = 0.85
    default_width, default_height = 1280, 720

    screen_info = pygame.display.Info()
    screen_width, screen_height = screen_info.current_w, screen_info.current_h
    if screen_width <= 0 or screen_height <= 0:
        return default_width, default_height

    aspect_ratio = VIRTUAL_WIDTH / VIRTUAL_HEIGHT
    max_width = screen_width * screen_fraction
    max_height = screen_height * screen_fraction

    width = min(max_width, max_height * aspect_ratio)
    height = width / aspect_ratio
    return round(width), round(height)


# Size of our actual window: a fraction of the detected screen,
# keeping the virtual resolution's aspect ratio.
WINDOW_WIDTH, WINDOW_HEIGHT = _window_size_for_current_screen()

BASE_DIR = pathlib.Path(__file__).parent

TEXTURES = {
    "shuffle": pygame.image.load(BASE_DIR / "assets" / "graphics" / "shuffle.png"),
    "auto": pygame.image.load(BASE_DIR / "assets" / "graphics" / "auto.png"),
    "eye_open": pygame.image.load(BASE_DIR / "assets" / "graphics" / "eye_open.png"),
    "eye_closed": pygame.image.load(BASE_DIR / "assets" / "graphics" / "eye_closed.png"),
    "search": pygame.image.load(BASE_DIR / "assets" / "graphics" / "search.png"),
    "undo": pygame.image.load(BASE_DIR / "assets" / "graphics" / "undo.png"),
    "redo": pygame.image.load(BASE_DIR / "assets" / "graphics" / "redo.png"),
}

# Register your frames, for instance:
# FRAMES = {
#     'my_frames': frames.generate_frames(TEXTURES['my_texture'], 16, 16)
# }
FRAMES = {}

# Register your sound from the sounds folder, for instance:
# SOUNDS = {
#     'my_sound': pygame.mixer.Sound(BASE_DIR / "assets"  / "sounds" / "my_sound.wav"),
# }
SOUNDS = {}

# Register your fonts from the fonts folder, for instance:
# FONTS = {
#     'small': pygame.font.Font(BASE_DIR / "assets"  / "fonts" / "font.ttf", 8)
# }
# (size on the 480x270 virtual canvas, bold). Font(None, ...) uses
# pygame's default font, no .ttf file of our own is needed.
FONT_SPECS = {
    # Face-guide letters (U/D/L/R/F/B) -- see view_3d.draw_face_guide.
    "guide": (15, True),
    # Plain (antialiased) text: InstructionsState's rows, PlayState's
    # button tooltips and search messages.
    "body": (14, False),
    "body_bold": (14, True),
    "small": (12, False),
}
# Virtual-size fonts, used for measuring/laying out text and for the
# pixel-art labels drawn on the canvas. Plain text is drawn through
# src/text.py instead, which rebuilds these at window resolution so it
# stays sharp after the canvas gets upscaled.
FONTS = {}
for _key, (_size, _bold) in FONT_SPECS.items():
    FONTS[_key] = pygame.font.Font(None, _size)
    FONTS[_key].set_bold(_bold)

# Blocky pixel-art labels (menu/instructions titles and buttons, the
# scramble timer): a real pixel font at its native 8px grid, rendered
# without antialiasing and enlarged by src/text.py's PixelLabel.
PIXEL_FONT_PATH = BASE_DIR / "assets" / "fonts" / "PressStart2P-Regular.ttf"
FONTS["pixel"] = pygame.font.Font(str(PIXEL_FONT_PATH), 8)
