"""
Transmutacion Arcana

This file contains the game settings: input bindings, window/board
layout constants, combat balance numbers, fonts, and textures. Board
tiles are still procedural placeholders (src/board/tile.py); the
combat portraits load the hand-authored pixel-art PNGs generated by
tools/generate_portraits.py -- swapping in different art later is a
matter of overwriting those PNGs (or pointing TEXTURES/ENEMY_ROSTER at
new files), not touching src/ui/hud.py.
"""

from pathlib import Path

import pygame

from gale import input_handler

input_handler.InputHandler.set_keyboard_action(input_handler.KEY_ESCAPE, "quit")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_KP_ENTER, "enter")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_RETURN, "enter")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_UP, "up")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_DOWN, "down")
input_handler.InputHandler.set_mouse_click_action(input_handler.MOUSE_BUTTON_1, "click")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_1, "power_fire")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_2, "power_shield")
input_handler.InputHandler.set_keyboard_action(input_handler.KEY_3, "power_stasis")

BASE_DIR = Path(__file__).parent
PORTRAITS_DIR = BASE_DIR / "assets" / "graphics" / "portraits"

TITLE = "Transmutacion Arcana"

VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 512

WINDOW_WIDTH = 1024
WINDOW_HEIGHT = 1024

# --- Board layout -----------------------------------------------------
BOARD_WIDTH = 8
BOARD_HEIGHT = 8
TILE_SIZE = 32

BOARD_PIXEL_WIDTH = BOARD_WIDTH * TILE_SIZE
BOARD_PIXEL_HEIGHT = BOARD_HEIGHT * TILE_SIZE

BOARD_X = (VIRTUAL_WIDTH - BOARD_PIXEL_WIDTH) // 2
BOARD_Y = 200

# --- Screen zones -------------------------------------------------------
# The screen is split, top to bottom, into: the combat zone (portraits,
# HP bars and essence counters), the board zone, and a bottom bar with
# the three power icons and the combat log.
COMBAT_ZONE = pygame.Rect(0, 0, VIRTUAL_WIDTH, BOARD_Y)
BOARD_ZONE = pygame.Rect(0, BOARD_Y, VIRTUAL_WIDTH, BOARD_PIXEL_HEIGHT + 16)
POWER_BAR_ZONE = pygame.Rect(
    0, BOARD_ZONE.bottom, VIRTUAL_WIDTH, VIRTUAL_HEIGHT - BOARD_ZONE.bottom
)

# --- Combat balance -------------------------------------------------------
PLAYER_MAX_HP = 100

DAMAGE_PER_STEEL_TILE = 8
ESSENCE_PER_GEM_TILE = 3
MAX_ESSENCE = 99

FIRE_POWER_DAMAGE = 40
SHIELD_POWER_HEAL = 30

ENEMY_TURN_DELAY = 0.6

# --- Tile kinds -------------------------------------------------------
# Matches src.board.tile.TileKind ordering: STEEL, RED, BLUE, PURPLE.
TILE_COLORS = {
    0: (176, 180, 188),  # Runas de Acero
    1: (204, 60, 60),  # Gemas Rojas
    2: (66, 132, 214),  # Gemas Azules
    3: (150, 72, 196),  # Gemas Moradas
}

ESSENCE_KIND_NAMES = {"red": "Roja", "blue": "Azul", "purple": "Morada"}

# --- Enemy roster (in order of appearance) --------------------------------
ENEMY_ROSTER = [
    {
        "name": "Homunculo de Hierro",
        "max_hp": 90,
        "attack": (8, 14),
        "color": (120, 120, 130),
        "sprite_file": "homunculo_hierro.png",
    },
    {
        "name": "Espectro Alquimico",
        "max_hp": 110,
        "attack": (10, 16),
        "color": (120, 90, 180),
        "sprite_file": "espectro_alquimico.png",
    },
    {
        "name": "Guardian de Cristal",
        "max_hp": 135,
        "attack": (12, 18),
        "color": (80, 160, 200),
        "sprite_file": "guardian_cristal.png",
    },
    {
        "name": "Dragon de Mercurio",
        "max_hp": 170,
        "attack": (14, 22),
        "color": (190, 80, 60),
        "sprite_file": "dragon_mercurio.png",
    },
]

PLAYER_SPRITE_FILE = "alquimista.png"

# TEXTURES holds every loaded pixel-art portrait, keyed by filename, so
# both the player and each ENEMY_ROSTER entry can be blitted by
# src.ui.hud.draw_portrait. pygame.image.load (without .convert_alpha)
# works before a display mode is set, same as the original match3
# project's texture loading in settings.py.
TEXTURES = {
    path.name: pygame.image.load(path)
    for path in PORTRAITS_DIR.glob("*.png")
}

BACKGROUND_COLOR = (18, 14, 26)

FONTS = {
    "small": pygame.font.Font(None, 14),
    "medium": pygame.font.Font(None, 22),
    "large": pygame.font.Font(None, 40),
    "huge": pygame.font.Font(None, 56),
}
