"""
UI / HUD helpers for the combat zone.

draw_portrait blits the pixel-art sprite generated by
tools/generate_portraits.py (settings.TEXTURES) inside a tinted frame;
if a caller ever passes image=None it falls back to a flat tinted
block, so this stays swappable -- callers (src.states.battle_state)
only pass a rect, a color, a label, and a sprite, never how it's
painted.
"""

from typing import List, Optional

import pygame

from gale.text import render_text

import settings
from src.rpg.essence import EssencePool
from src.rpg.powers import POWERS

BAR_BG = (40, 38, 48)
BAR_BORDER = (18, 17, 22)
HP_FILL = (214, 64, 64)
HP_FILL_LOW = (232, 160, 40)
TEXT_LIGHT = (235, 235, 240)


def draw_bar(
    surface: pygame.Surface,
    rect: pygame.Rect,
    ratio: float,
    fill_color,
    bg_color=BAR_BG,
    border_color=BAR_BORDER,
) -> None:
    ratio = max(0.0, min(1.0, ratio))
    pygame.draw.rect(surface, bg_color, rect, border_radius=4)
    if ratio > 0:
        fill_rect = pygame.Rect(rect.x, rect.y, int(rect.width * ratio), rect.height)
        pygame.draw.rect(surface, fill_color, fill_rect, border_radius=4)
    pygame.draw.rect(surface, border_color, rect, width=2, border_radius=4)


def draw_hp_bar(surface: pygame.Surface, rect: pygame.Rect, name: str, hp: int, max_hp: int) -> None:
    ratio = hp / max_hp if max_hp else 0
    color = HP_FILL if ratio > 0.3 else HP_FILL_LOW
    draw_bar(surface, rect, ratio, color)
    render_text(
        surface,
        f"{name}  {hp}/{max_hp}",
        settings.FONTS["small"],
        rect.centerx,
        rect.centery,
        TEXT_LIGHT,
        center=True,
        shadowed=True,
    )


def draw_portrait(
    surface: pygame.Surface,
    rect: pygame.Rect,
    color,
    label: str,
    image: Optional[pygame.Surface] = None,
) -> None:
    pygame.draw.rect(surface, (24, 22, 32), rect, border_radius=8)

    if image is not None:
        sprite = pygame.transform.scale(image, (rect.width - 6, rect.height - 6))
        surface.blit(sprite, (rect.x + 3, rect.y + 3))
    else:
        # No sprite available: fall back to a flat tinted block.
        inner = rect.inflate(-6, -6)
        pygame.draw.rect(surface, color, inner, border_radius=6)

    pygame.draw.rect(surface, color, rect, width=3, border_radius=8)

    # Center the label under the portrait, but clamp it so a long name
    # (e.g. "Homunculo de Hierro" under the enemy portrait, hard against
    # the right edge) never renders past the screen bounds.
    font = settings.FONTS["small"]
    half_width = font.size(label)[0] // 2
    label_x = min(
        max(rect.centerx, half_width + 4), settings.VIRTUAL_WIDTH - half_width - 4
    )

    render_text(
        surface,
        label,
        font,
        label_x,
        rect.bottom + 10,
        TEXT_LIGHT,
        center=True,
        shadowed=True,
    )


def draw_essence_row(surface: pygame.Surface, x: int, y: int, essence: EssencePool) -> None:
    kinds = (
        ("red", settings.TILE_COLORS[1]),
        ("blue", settings.TILE_COLORS[2]),
        ("purple", settings.TILE_COLORS[3]),
    )
    box = 14
    gap = 54

    for index, (kind, color) in enumerate(kinds):
        box_x = x + index * gap
        rect = pygame.Rect(box_x, y, box, box)
        pygame.draw.rect(surface, color, rect, border_radius=3)
        pygame.draw.rect(surface, (18, 17, 22), rect, width=2, border_radius=3)
        render_text(
            surface,
            str(getattr(essence, kind)),
            settings.FONTS["small"],
            box_x + box + 4,
            y - 1,
            TEXT_LIGHT,
            shadowed=True,
        )


def draw_power_bar(
    surface: pygame.Surface,
    essence: EssencePool,
    enemy_stunned: bool,
) -> List[pygame.Rect]:
    """
    Draws the three power icons inside settings.POWER_BAR_ZONE and
    returns their clickable rects (same order as POWERS.values()) so
    the caller can hit-test mouse clicks against them.
    """
    zone = settings.POWER_BAR_ZONE
    powers = list(POWERS.values())
    icon_size = 40
    gap = zone.width // len(powers)
    rects = []

    for index, power in enumerate(powers):
        cx = zone.x + gap * index + gap // 2
        rect = pygame.Rect(0, 0, icon_size, icon_size)
        rect.center = (cx, zone.centery - 6)
        affordable = essence.has_enough(power.essence_kind, power.cost)

        color = power.color if affordable else tuple(c // 3 for c in power.color)
        pygame.draw.rect(surface, color, rect, border_radius=6)
        pygame.draw.rect(surface, (18, 17, 22), rect, width=2, border_radius=6)
        render_text(
            surface,
            power.key_label,
            settings.FONTS["small"],
            rect.centerx,
            rect.centery,
            TEXT_LIGHT,
            center=True,
            shadowed=True,
        )
        render_text(
            surface,
            f"{power.cost}",
            settings.FONTS["small"],
            rect.centerx,
            rect.bottom + 10,
            TEXT_LIGHT,
            center=True,
            shadowed=True,
        )
        rects.append(rect)

    if enemy_stunned:
        render_text(
            surface,
            "Enemigo aturdido",
            settings.FONTS["small"],
            zone.right - 6,
            zone.y + 2,
            (255, 220, 120),
            shadowed=True,
        )

    return rects


def draw_log(surface: pygame.Surface, x: int, y: int, messages: List[str]) -> None:
    for index, message in enumerate(messages):
        render_text(
            surface,
            message,
            settings.FONTS["small"],
            x,
            y + index * 14,
            (200, 200, 210),
            shadowed=True,
        )
